apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitoring
  labels:
    app: myweb
spec:
  selector:
    matchLabels:
      app: myweb
    
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /metrics
    targetPort: 8000