apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  namespace: myapp
  labels:
    app: myweb
spec:
  replicas: 2   
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: gcr.io/artful-fragment-346911/myappv3
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            protocol: TCP
            
#args: ['cat','../.git/COMMIT_EDITMSG']