apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb
  name: myweb-service
  namespace: myapp
spec:
  selector:
    app: myweb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
status:
  LoadBalancer: {}
