apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb
  name: myweb-service
  namespace: default
spec:
  selector:
    app: myweb
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 3000
  selctor:
    app: myweb
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitoring
  labels:
    app: myweb
spec:
  selector:
    matchLabels:
      app: myweb
      release: prometheus
  endpoints:
  - port: web
    path: /metrics
    