apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb
  name: myweb-service
  namespace: default
spec:
  selector:
    app: myweb
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-node-app
  labels:
    app: myweb
spec:
  endpoints:
  - port: web
    path: /metrics
    targetPort: 3000
  
  selector:
    matchLabels:
      app: myweb
    
  namespaceSelector:
    any: true
  
    