name: docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: artful-fragment-346911
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true  

      - name: build doker file
        run: docker build -t gcr.io/artful-fragment-346911/myappv3:$GITHUB_SHA .

      - name: config
        run: |-
          gcloud auth configure-docker --quiet

      - name: push image
        run: docker push gcr.io/artful-fragment-346911/myappv3:$GITHUB_SHA        

      - name: connect kube
        run: gcloud container clusters get-credentials my-sec-cluster --region us-east4 --project artful-fragment-346911
      
      - name: to dep namespace
        run: kubectl apply -f kubeFiles/namespace.yaml

      - name: to dep kubernetes
        run: kubectl apply -f kubeFiles/deployment.yaml  

      - name: to image kubernetes        
        run: kubectl set image deployment/myweb myweb=gcr.io/artful-fragment-346911/myappv3:$GITHUB_SHA  -n myapp

      - name: to service kubernetes
        run: kubectl apply -f kubeFiles/service.yaml --validate=false  

 